### ISSUE TITLE
Not working after upgrade to Atom Version 1.23.1

### ISSUE THREAD

**Issue by AnthonyRoberts** [lonekorean/atom-autocomplete-font-awesome#6] opened 2017-12-14 16:56 UTC
Since updating Atom to version 1.23.1 this no longer works unless the document type is set to HTML. It was working in version 1.22.1 (for text, html, php etc.)

Most of my apps start life as index.php

**Comment by lonekorean** [comment] 2017-12-16 17:40
Hi Anthony, thanks for this.

It appears to be a new bug Atom's core autocomplete-plus package. One of the effects is that dashes are no longer recognized as part of a term, so "fa-" stopped working. See PR here: https://github.com/atom/autocomplete-plus/pull/928 .

Looks like it's been merged and tagged for release, hopefully with Atom 1.24 (next release). I'll keep an eye on it.

**Comment by AnthonyRoberts** [comment] 2018-01-10 10:25
Excellent news; release 1.23.3 of Atom has fixed the problem.

**Comment by lonekorean** [comment] 2018-01-10 11:35
Funny story, I actually spent a few hours yesterday on a workaround... then poof, Atom released a new version the same night. :)

However, there seems to be a regression that causes "fa-" to be inserted twice: https://github.com/atom/autocomplete-plus/issues/939

Still working to fix that bit.

**Comment by AnthonyRoberts** [comment] 2018-01-10 11:46
Just noticed that I get the double fa as well

Unrelated question, are you the same Will Boyd that wrote Sublime SFTP? Before switching to Atom, I was a fan of Sublime Text and WBond SFTP was essential for my workflow. Sounds like software you write is making my life easier in every editor I use.

**Comment by lonekorean** [comment] 2018-01-11 18:35
Alright, got a workaround in place, so I think everything's good again. Just published v0.2.4, give it a spin and let me know if you have any issues.

And no, that's Will Bond. He seems like a cool guy though. :)

**Closed by lonekorean** 2018-01-11 18:35 UTC
